build:
  version: "2.0"

  accounts-contact-info:
    message: "accounts related APIs information"
    contact-details:
      name: "qa"
      email: "qa@bank.com"
    contact-support:
      - 1234-567
      - 1234-568