cards-contact-info:
  message: "cards related APIs information"
  contact-details:
    name: "local"
    email: "local@bank.com"
  contact-support:
    - 1234-567
    - 1234-568

build:
  version: "1.0"