server:
  port: 8071

# classpath or filesystem approach for reading configuration properties

#spring:
#  application:
#    name: "configserver"
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: "classpath:/config"

# git approach for reading configuration properties

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Ravikumar7284/bank-microservices-config-properties.git"
          username: "Ravikumar7284"
          password: "***************"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true